name: meeseeks
description: "I'm Mr. Meeseeks, look at me!"

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0-18.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  google_fonts: 6.2.1

  # Routing
  go_router: 13.2.3
  url_strategy: 0.2.0

  # State managment
  flutter_riverpod: 3.0.0-dev.3
  riverpod_annotation: 3.0.0-dev.3

  # Preferences
  shared_preferences: 2.2.2

  # Native enhancements
  flutter_native_splash: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linters
  flutter_lints: 3.0.2
  custom_lint: 0.6.4
  riverpod_lint: 3.0.0-dev.4
  nilts: 0.12.1

  # Generates files
  build_runner: 2.4.9

  # Navigation generation
  go_router_builder: 2.5.0

  # State Management generation
  riverpod_generator: 3.0.0-dev.11

  # Native enhancements
  flutter_launcher_icons: 0.13.1

dependency_overrides:
  custom_lint_builder: 0.6.0 # Blocked by [riverpod_lint]
  custom_lint_core: 0.6.0 # Blocked by [riverpod_lint]

flutter:
  uses-material-design: true
